# Generated by Django 4.1.3 on 2022-11-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='purchaser',
        ),
    ]
